name: "sac"

# experiment parameters
eval: True
eval_interval: 3
eval_episodes: 1
save_model: True  # save model after evaluation
save_all: False
save_best: True
log_interval: 5 # log data interval to wandb 
log_path: "logs/"  # config and model log path
load_model: False
model_path: False

entropy_tuning: True
alpha: 1.
alpha_lr: 3e-4
lr: 0.002
policy_lr: 0.0002
gamma: 0.99
tau: 5e-3
td_target_update_interval: 1
updates_per_step: 1
reward_scale: 1.0
grad_clip: null

value_net_kwargs: 
    hidden_dim: 256 # neuron per layer = hidden_dim*num_parallels
    num_layers: 2
    num_parallels: 1
    use_layernorm: False
    use_resnet: True
    compile_method: "trace" # [trace, compile, None]

policy_net_kwargs: 
    architecture: "graph" # [plain, graph]
    hidden_dim: 8
    num_layers: 1
    num_parallels: 1 # number of parallel layers
    use_layernorm: False
    use_resnet: False
    compile_method: "trace" # [trace, compile, None]

    # only useful for graph architecture
    graph: 
        num_gcn_layers: 1 
        embedding_dim: 8
        init_positive_edge_weight: 0.5
        init_negative_edge_weight: -0.5
